name: TheBlueHatsPit
main: me.stevemmmmm.thehypixelpit.core.Main
version: 1.0
depend: [ProtocolLib]
commands:
  pitenchant:
    description: Use it to enchant some weapons xD xD
    usage: /pitenchant
  mysticenchants:
    description: Lists the enchants
    usage: /mysticenchants
  pitabout:
    description: Information about this plugin
    usage: /pitabout
  givefreshitem:
    description: Gives a fresh item
    usage: /givefreshitem
  giveprot:
    description: Gives prot
    usage: /giveprot
  setgold:
    description: Sets gold
    usage: /setgold
  givebread:
    description: Gives bread
    usage: /givebread
  spawn:
    description: Sends the player to spawn
    usage: /spawn
  respawn:
    description: Sends the player to spawn
    usage: /respawn
  givearrows:
    description: Gives arrows
    usage: /givearrows
  giveobsidian:
    description: Gives obby
    usage: /giveobsidian
  duel:
    description: Duels a player
    usage: /duel